services:
  database:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-docker}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-docker}
      - POSTGRES_DB=${POSTGRES_DB:-export}
    ports:
      - "5432:5432"
